insert into products (name, price, category) values
-- Porções
('Batata Frita com Bacon e Catupiry/Cheddar', 27.90, 'Porções'),
('Batata Frita Individual', 19.90, 'Porções'),
('Anéis de Cebola (12 un)', 27.90, 'Porções'),
('Nuggets com Queijo (10 un)', 27.90, 'Porções'),
-- Milkshake
('Milkshake Ovomaltine', 26.90, 'Milkshake'),
('Milkshake Pacoquinha', 26.90, 'Milkshake'),
('Milkshake Morango', 26.90, 'Milkshake'),
-- Lanches
('Spicy Burguer', 35.90, 'Lanches'),
('Tuki Burguer', 28.90, 'Lanches'),
('Tuki Kids', 24.90, 'Lanches'),
('Catan Burguer', 36.90, 'Lanches'),
('Karuba Burguer', 36.90, 'Lanches'),
('Ubongo Burguer', 39.90, 'Lanches'),
('Odin Burguer', 39.90, 'Lanches'),
('Clank Burguer', 36.90, 'Lanches'),
('Dobble Burguer', 36.90, 'Lanches'),
('Verdant', 39.90, 'Lanches'),
-- Combos
('Combo Odin', 54.80, 'Combos'),
('Combo Dobble', 51.80, 'Combos'),
('Combo Tuki Kids', 38.90, 'Combos'),
('Combo Karuba', 51.80, 'Combos'),
('Combo Verdant', 54.80, 'Combos'),
('Combo Clank', 51.80, 'Combos'),
('Combo Ubongo', 54.80, 'Combos'),
('Combo Catan', 51.80, 'Combos'),
('Combo Tuki', 43.80, 'Combos'),
('Combo Spicy Burguer', 51.80, 'Combos'),
-- Drinks Alcoólicos
('Marrakesh', 22.90, 'Drinks Alcoólicos'),
('Rancho Elétrico', 16.90, 'Drinks Alcoólicos'),
('Love Letter', 22.90, 'Drinks Alcoólicos'),
('Vale dos Monstros', 24.90, 'Drinks Alcoólicos'),
('Rum & Bones', 24.90, 'Drinks Alcoólicos'),
('Poção de HP', 24.90, 'Drinks Alcoólicos'),
('Poção de Estamina', 24.90, 'Drinks Alcoólicos'),
('Takenoko', 23.90, 'Drinks Alcoólicos'),
('Ouch', 18.90, 'Drinks Alcoólicos'),
('Dive', 25.90, 'Drinks Alcoólicos'),
('Skullmule', 28.90, 'Drinks Alcoólicos'),
('Nosferatu', 24.90, 'Drinks Alcoólicos'),
-- Gins com Especiarias
('Gin Blueberry', 28.90, 'Gins com Especiarias'),
('Gin Morango com Pimenta', 28.90, 'Gins com Especiarias'),
('Gin Tropical Especiarias', 28.90, 'Gins com Especiarias'),
-- Drinks Não Alcoólicos
('Blood Rage sem Álcool', 22.90, 'Drinks Não Alcoólicos'),
('Piratas Kings Gold sem Álcool', 22.90, 'Drinks Não Alcoólicos'),
('Dive sem Álcool', 22.90, 'Drinks Não Alcoólicos'),
('Love Letter sem Álcool', 22.90, 'Drinks Não Alcoólicos'),
('Marrakesh sem Álcool', 22.90, 'Drinks Não Alcoólicos'),
('Rum And Bones sem Álcool', 22.90, 'Drinks Não Alcoólicos'),
('Poção HP sem Álcool', 22.90, 'Drinks Não Alcoólicos'),
('Poção Mana sem Álcool', 22.90, 'Drinks Não Alcoólicos'),
-- Bebidas
('Chopp Brahma 380ml', 11.90, 'Bebidas'),
('Long Neck Heineken', 9.90, 'Bebidas'),
('Água Mineral sem Gás', 5.00, 'Bebidas'),
('Água Mineral com Gás', 5.00, 'Bebidas'),
('Refrigerante Lata 350ml', 6.50, 'Bebidas'),
('Suco Morango 380ml', 12.00, 'Bebidas'),
('Suco Laranja 380ml', 13.00, 'Bebidas'),
('Suco Maracujá 380ml', 14.00, 'Bebidas'),
('Suco Frutas Vermelhas 380ml', 15.00, 'Bebidas'),
('Suco Abacaxi 380ml', 14.00, 'Bebidas'),
('Suco Abacaxi com Hortelã 380ml', 14.00, 'Bebidas'),
('Budweiser Long Neck', 8.90, 'Bebidas');
